In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv('Article_top_Data.csv')
data.head()

,Unnamed: 0,Date,StoreNumber,CashRegisterNumber,ReceiptNumber,ReceiptRowNumber,Time,ArticleNumber,ArticleName,Quantity,Timestamp,Month,Day,Hour,Group
0,4,2022-01-03,1001,1,296,5,09:21:14,419727,"GL H-Milch 3,5% 1L VLOG",1.0,2022-01-03 09:21:14,1,0,9,Milch
1,6,2022-01-03,1001,1,296,7,09:21:14,999999998025,Pfandartikel (Tandem) - EW,1.0,2022-01-03 09:21:14,1,0,9,Pfandartikel
2,7,2022-01-03,1001,1,296,8,09:21:14,435066,Schlaufentragetasche ST,1.0,2022-01-03 09:21:14,1,0,9,Schlaufentragetasche ST
3,19,2022-01-03,1001,1,300,1,09:25:34,421791,BO-Laugenbreze 1ST,1.0,2022-01-03 09:25:34,1,0,9,BO-Laugenbreze 1ST
4,20,2022-01-03,1001,1,300,2,09:25:34,421791,BO-Laugenbreze 1ST,1.0,2022-01-03 09:25:34,1,0,9,BO-Laugenbreze 1ST

In [3]:
print(data.StoreNumber.unique())
encoder = LabelEncoder()
data.StoreNumber = encoder.fit_transform(data.StoreNumber)
print(data.StoreNumber.unique())
# data.StoreNumber = data.StoreNumber.apply(lambda x: f'store_{x}')
# print(data.StoreNumber.unique())

[1001 1007 1028 1033 1053 1098 1223 1303 1311 1417 1436 1487 1504 2801]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]

In [4]:
sales = data.groupby(['Date','StoreNumber', 'CashRegisterNumber', 'ReceiptNumber','Group'], as_index=False).aggregate({'Quantity': 'sum'})
sales.head()

,Date,StoreNumber,CashRegisterNumber,ReceiptNumber,Group,Quantity
0,2022-01-03,0,1,296,Milch,1.0
1,2022-01-03,0,1,296,Pfandartikel,1.0
2,2022-01-03,0,1,296,Schlaufentragetasche ST,1.0
3,2022-01-03,0,1,300,BO-Laugenbreze 1ST,2.0
4,2022-01-03,0,1,302,Avocado vorgereift ST,1.0

In [5]:
# Feature matrix with shape (n_series x time_observations)
ts_series = sales.pivot(index=['Date','StoreNumber','CashRegisterNumber', 'ReceiptNumber'], columns=['Group'])
ts_series = ts_series.fillna(0)
ts_series.head(10)

                                                                        Quantity  \
Group                                                   AugustinerHellMW1x0,5LFL
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                                0.0
                                          300                                0.0
                                          302                                0.0
                                          303                                0.0
                                          305                                0.0
                                          306                                0.0
                                          307                                0.0
                       2                  2                                  0.0
                                          4                                  0.0
                                          5                                  0.0

                                                                               \
Group                                                   Avocado vorgereift ST
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                             0.0
                                          300                             0.0
                                          302                             1.0
                                          303                             0.0
                                          305                             0.0
                                          306                             0.0
                                          307                             0.0
                       2                  2                               0.0
                                          4                               2.0
                                          5                               0.0

                                                                            \
Group                                                   BO-Laugenbreze 1ST
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                          0.0
                                          300                          2.0
                                          302                          0.0
                                          303                          0.0
                                          305                          0.0
                                          306                          0.0
                                          307                          0.0
                       2                  2                            0.0
                                          4                            0.0
                                          5                            0.0

                                                                      \
Group                                                   Bananen Lose
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                    0.0
                                          300                    0.0
                                          302                    0.0
                                          303                    0.0
                                          305                    0.0
                                          306                    0.0
                                          307                    0.0
                       2                  2                      0.0
                                          4                      0.0
                                          5                      0.0

                                                                   \
Group                                                   Broetchen
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                 0.0
                                          300                 0.0
                                          302                 0.0
                                          303                 0.0
                                          305                 0.0
                                          306                 0.0
                                          307                 0.0
                       2                  2                   0.0
                                          4                   6.0
                                          5                   0.0

                                                                                \
Group                                                   GL Sahne 30% 200g VLOG
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                              0.0
                                          300                              0.0
                                          302                              0.0
                                          303                              0.0
                                          305                              0.0
                                          306                              0.0
                                          307                              0.0
                       2                  2                                0.0
                                          4                                2.0
                                          5                                0.0

                                                                   \
Group                                                   Gurken ST
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                 0.0
                                          300                 0.0
                                          302                 0.0
                                          303                 0.0
                                          305                 0.0
                                          306                 0.0
                                          307                 0.0
                       2                  2                   0.0
                                          4                   3.0
                                          5                   0.0

                                                                       \
Group                                                   Kiwi Gruen ST
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                     0.0
                                          300                     0.0
                                          302                     0.0
                                          303                     0.0
                                          305                     0.0
                                          306                     0.0
                                          307                     0.0
                       2                  2                       0.0
                                          4                       0.0
                                          5                       0.0

                                                                                  \
Group                                                   M.I. Mozzarella oGt 125g
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                                0.0
                                          300                                0.0
                                          302                                0.0
                                          303                                0.0
                                          305                                0.0
                                          306                                0.0
                                          307                                0.0
                       2                  2                                  4.0
                                          4                                  0.0
                                          5                                  0.0

                                                                            \
Group                                                   Milch Pfandartikel
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296             1.0          1.0
                                          300             0.0          0.0
                                          302             0.0          0.0
                                          303             0.0          0.0
                                          305             0.0          1.0
                                          306             1.0          0.0
                                          307            10.0          0.0
                       2                  2               1.0          1.0
                                          4               0.0          0.0
                                          5               0.0          6.0

                                                                                  \
Group                                                   SammelNr. Lose Backwaren
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                                0.0
                                          300                                0.0
                                          302                                0.0
                                          303                                0.0
                                          305                                0.0
                                          306                                0.0
                                          307                                0.0
                       2                  2                                  0.0
                                          4                                  0.0
                                          5                                  0.0

                                                                                 \
Group                                                   Schlaufentragetasche ST
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                               1.0
                                          300                               0.0
                                          302                               0.0
                                          303                               0.0
                                          305                               0.0
                                          306                               0.0
                                          307                               0.0
                       2                  2                                 0.0
                                          4                                 0.0
                                          5                                 0.0

                                                                          \
Group                                                   VL Eier BH 10ST
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                        0.0
                                          300                        0.0
                                          302                        0.0
                                          303                        1.0
                                          305                        0.0
                                          306                        0.0
                                          307                        0.0
                       2                  2                          0.0
                                          4                          1.0
                                          5                          0.0


Group                                                   Zeitschriften 7%
Date       StoreNumber CashRegisterNumber ReceiptNumber
2022-01-03 0           1                  296                        0.0
                                          300                        0.0
                                          302                        0.0
                                          303                        0.0
                                          305                        0.0
                                          306                        0.0
                                          307                        0.0
                       2                  2                          0.0
                                          4                          0.0
                                          5                          0.0

In [6]:
ts_series.reset_index(1, inplace=True)
ts_series.head()

                                            StoreNumber  \
Group
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                     0
                              300                     0
                              302                     0
                              303                     0
                              305                     0

                                                            Quantity  \
Group                                       AugustinerHellMW1x0,5LFL
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                0.0
                              300                                0.0
                              302                                0.0
                              303                                0.0
                              305                                0.0

                                                                   \
Group                                       Avocado vorgereift ST
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                             0.0
                              300                             0.0
                              302                             1.0
                              303                             0.0
                              305                             0.0

                                                                             \
Group                                       BO-Laugenbreze 1ST Bananen Lose
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                          0.0          0.0
                              300                          2.0          0.0
                              302                          0.0          0.0
                              303                          0.0          0.0
                              305                          0.0          0.0

                                                                              \
Group                                       Broetchen GL Sahne 30% 200g VLOG
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                 0.0                    0.0
                              300                 0.0                    0.0
                              302                 0.0                    0.0
                              303                 0.0                    0.0
                              305                 0.0                    0.0

                                                                     \
Group                                       Gurken ST Kiwi Gruen ST
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                 0.0           0.0
                              300                 0.0           0.0
                              302                 0.0           0.0
                              303                 0.0           0.0
                              305                 0.0           0.0

                                                                            \
Group                                       M.I. Mozzarella oGt 125g Milch
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                0.0   1.0
                              300                                0.0   0.0
                              302                                0.0   0.0
                              303                                0.0   0.0
                              305                                0.0   0.0

                                                          \
Group                                       Pfandartikel
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                    1.0
                              300                    0.0
                              302                    0.0
                              303                    0.0
                              305                    1.0

                                                                      \
Group                                       SammelNr. Lose Backwaren
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                0.0
                              300                                0.0
                              302                                0.0
                              303                                0.0
                              305                                0.0

                                                                     \
Group                                       Schlaufentragetasche ST
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                               1.0
                              300                               0.0
                              302                               0.0
                              303                               0.0
                              305                               0.0


Group                                       VL Eier BH 10ST  Zeitschriften 7%
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                        0.0              0.0
                              300                        0.0              0.0
                              302                        0.0              0.0
                              303                        1.0              0.0
                              305                        0.0              0.0

In [7]:
ts_series.columns = ts_series.columns.droplevel(0)
display(ts_series.head(2))
ts_series.rename(columns={'':'StoreNumber'}, inplace=True)
display(ts_series.head(2))

Group                                           AugustinerHellMW1x0,5LFL  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296            0                       0.0
                              300            0                       0.0

Group                                        Avocado vorgereift ST  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                              0.0
                              300                              0.0

Group                                        BO-Laugenbreze 1ST  Bananen Lose  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                           0.0           0.0
                              300                           2.0           0.0

Group                                        Broetchen  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                  0.0
                              300                  0.0

Group                                        GL Sahne 30% 200g VLOG  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                               0.0
                              300                               0.0

Group                                        Gurken ST  Kiwi Gruen ST  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                  0.0            0.0
                              300                  0.0            0.0

Group                                        M.I. Mozzarella oGt 125g  Milch  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                 0.0    1.0
                              300                                 0.0    0.0

Group                                        Pfandartikel  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                     1.0
                              300                     0.0

Group                                        SammelNr. Lose Backwaren  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                 0.0
                              300                                 0.0

Group                                        Schlaufentragetasche ST  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                1.0
                              300                                0.0

Group                                        VL Eier BH 10ST   \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                         0.0
                              300                         0.0

Group                                        Zeitschriften 7%
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                         0.0
                              300                         0.0

Group                                        StoreNumber  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                      0
                              300                      0

Group                                        AugustinerHellMW1x0,5LFL  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                 0.0
                              300                                 0.0

Group                                        Avocado vorgereift ST  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                              0.0
                              300                              0.0

Group                                        BO-Laugenbreze 1ST  Bananen Lose  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                           0.0           0.0
                              300                           2.0           0.0

Group                                        Broetchen  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                  0.0
                              300                  0.0

Group                                        GL Sahne 30% 200g VLOG  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                               0.0
                              300                               0.0

Group                                        Gurken ST  Kiwi Gruen ST  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                  0.0            0.0
                              300                  0.0            0.0

Group                                        M.I. Mozzarella oGt 125g  Milch  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                 0.0    1.0
                              300                                 0.0    0.0

Group                                        Pfandartikel  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                     1.0
                              300                     0.0

Group                                        SammelNr. Lose Backwaren  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                 0.0
                              300                                 0.0

Group                                        Schlaufentragetasche ST  \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                                1.0
                              300                                0.0

Group                                        VL Eier BH 10ST   \
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                         0.0
                              300                         0.0

Group                                        Zeitschriften 7%
Date       CashRegisterNumber ReceiptNumber
2022-01-03 1                  296                         0.0
                              300                         0.0

In [8]:
ts_series.values

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [13.,  0.,  0., ...,  0.,  0.,  0.],
       [13.,  0.,  0., ...,  0.,  0.,  0.],
       [13.,  0.,  0., ...,  0.,  0.,  0.]])

In [9]:
ts_series.columns = ['StoreNumber','Augustiner','Avocado','BO-Laugenbreze','Bananen','Broetchen','GL_Sahne',
                 'Gurken','Kiwi_Gruen','Mozzarella','Milch','Pfandartikel','SammelNr','Schlaufentragetasche','VL_Eier','Zeitschriften']
ts_series.columns

Index(['StoreNumber', 'Augustiner', 'Avocado', 'BO-Laugenbreze', 'Bananen',
       'Broetchen', 'GL_Sahne', 'Gurken', 'Kiwi_Gruen', 'Mozzarella', 'Milch',
       'Pfandartikel', 'SammelNr', 'Schlaufentragetasche', 'VL_Eier',
       'Zeitschriften'],
      dtype='object')

In [10]:
ts_series.columns

Index(['StoreNumber', 'Augustiner', 'Avocado', 'BO-Laugenbreze', 'Bananen',
       'Broetchen', 'GL_Sahne', 'Gurken', 'Kiwi_Gruen', 'Mozzarella', 'Milch',
       'Pfandartikel', 'SammelNr', 'Schlaufentragetasche', 'VL_Eier',
       'Zeitschriften'],
      dtype='object')

In [11]:
ts_series.shape

(2137806, 16)

In [29]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

# 输入数据
sales_data = ts_series.to_numpy()
labels = np.array(ts_series.StoreNumber.values)

In [30]:
# 数据预处理
normalized_data = sales_data / np.max(sales_data)  # 归一化数据
num_classes = len(np.unique(labels))  # 标签类别数量
print(normalized_data[:3])
print(labels[:3])

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.00016861 0.00016861
  0.         0.00016861 0.         0.        ]
 [0.         0.         0.         0.00033721 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.00016861 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]]
[0 0 0]

In [31]:
# 构建输入特征和标签
X = normalized_data[:, 1:]  # 输入特征（前两个销售数量）
y = labels

In [32]:
# 转换数据形状为LSTM所需的三维格式：[样本数，时间步长，特征数]
X = np.reshape(X, (X.shape[0], 1, X.shape[1]))

In [33]:
# 将标签进行独热编码
y = np.eye(num_classes)[y]

In [36]:
# 构建LSTM模型
model = Sequential()
model.add(LSTM(50, input_shape=(1, 15)))  # 50个LSTM单元
model.add(Dense(num_classes, activation='softmax'))  # 输出层，使用softmax激活函数进行多类别分类

In [37]:
# 编译模型
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 模型训练
model.fit(X, y, epochs=100, batch_size=1, verbose=2)

Epoch 1/100

KeyboardInterrupt:

In [ ]:
# 使用模型进行预测
new_input = np.array([[5, 3]]) / np.max(sales_data)  # 新的输入特征
new_input = np.reshape(new_input, (new_input.shape[0], 1, new_input.shape[1]))  # 转换数据形状
predicted_output = model.predict(new_input)

predicted_label = np.argmax(predicted_output)

print("预测的标签为:", predicted_label)